name: Publish to Docker Hub
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - '**.md'
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: drakeaan/code-server-azure:latest,drakeaan/code-server-azure:3.12.0
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
